def main_menu():
    print("+-----------------------------------------+")
    print("| Main Menu                               |")
    print("+-----------------------------------------+")
    print("| 1. Player Performance Queries           |")
    print("| 2. Team Performance Queries             |")
    print("| 3. Game Statistics Queries              |")
    print("| 4. Event Statistics Queries             |")
    print("| 5. List All Teams                       |")
    print("| 6. Season Rankings                      |")
    print("| 7. Scratches Data                       |")
    print("| 8. Advanced Analytics Queries           |")
    print("| 9. Exit                                 |")
    print("+-----------------------------------------+")
    return input("Enter your choice: ")
